/*
   Quantum Break final temporal resolve composite pass.

   Native path:
   - samples three pre-reprojected history textures generated by the compute prepass
   - samples current color and depth with the current jitter offset
   - applies the four SSAA/TAA jitter offsets
   - resolves the 3 history samples plus the current sample into the final image
   - preserves the game's film grain behavior during the resolve
   - outputs final depth and then applies display mapping

   Luma SR path:
   - bypasses the native temporal resolve when LumaSettings.SRType > 0
   - samples the already upscaled SR color and matching depth instead
   - still performs the final display-mapping stage

   Important:
   - this is the best SR insertion point because it owns the final temporal composite
   - the compute prepass prepares history, but this shader performs the final resolve
*/
#include "./Includes/quantum_break_common.hlsli"

cbuffer ssaa : register(b1)
{
   float4x4 g_mSSAAClipToPreviousClip[3] : packoffset(c0);
   float2 g_vSSAAJitterOffset[4] : packoffset(c12);
   float2 g_vTAASourceRes : packoffset(c15.z);
   float2 g_vInvTAASourceRes : packoffset(c16);
};

SamplerState g_sLinearClamp : register(s0);
Texture2D<float4> g_tClipDepth : register(t0);
Texture2D<float4> g_sFilmGrain : register(t1);
Texture2D<float4> g_tColor : register(t2);
Texture2D<float4> g_tPreviousColor[3] : register(t3);

static float2 gl_FragCoord;
static float gl_FragDepth;
static float3 SV_Target;

struct SPIRV_Cross_Input
{
   noperspective float4 gl_FragCoord : SV_Position;
};

struct SPIRV_Cross_Output
{
   float3 SV_Target : SV_Target0;
   float gl_FragDepth : SV_Depth;
};

int cvt_f32_i32(float v)
{
   uint abs_bits = asuint(v) & 0x7fffffffu;
   bool is_nan = abs_bits > 0x7f800000u;
   return is_nan ? 0 : ((v < (-2147483648.0f)) ? int(0x80000000) : ((v > 2147483520.0f) ? 2147483647 : int(v)));
}

void frag_main()
{

   float4 _104 = g_sFilmGrain.Load(
       int3(uint2(uint(cvt_f32_i32(float(uint(cvt_f32_i32(gl_FragCoord.x + float(g_vTonemapNoiseOffset.x)) & 511)))),
                  uint(cvt_f32_i32(float(uint(cvt_f32_i32(gl_FragCoord.y + float(g_vTonemapNoiseOffset.y)) & 511))))),
            0u));
   float _111 = (CUSTOM_GRAIN_TYPE == 0.f) ? g_fTonemapNoiseIntensity * CUSTOM_GRAIN_STRENGTH : 0.f;

   float _113 = (1.0f - _111) * 0.5f;
   float _117 = (_104.x * _111) + _113;
   float _118 = _113 + (_104.y * _111);
   float _119 = _113 + (_104.z * _111);
   float _124 = g_vInvScreenRes.x;
   float _125 = g_vInvScreenRes.y;

   float2 scaled_uv = gl_FragCoord * g_vInvScreenRes;
   if (LumaSettings.SRType > 0)
   {
      float4 sr_color = g_tColor.Sample(g_sLinearClamp, scaled_uv);
      float4 sr_depth = g_tClipDepth.Sample(g_sLinearClamp, scaled_uv);
      gl_FragDepth = sr_depth.x;
      SV_Target = sr_color.rgb;
      if (CUSTOM_GRAIN_TYPE == 0.f)
      {
         SV_Target = float3(
             (sr_color.r < 0.5f) ? (1.0f - (((1.0f - sr_color.r) * 0.5f) / _117))
                                 : (sr_color.r / mad(0.5f - _117, 2.0f, 1.0f)),
             (sr_color.g < 0.5f) ? (1.0f - (((1.0f - sr_color.g) * 0.5f) / _118))
                                 : (sr_color.g / mad(0.5f - _118, 2.0f, 1.0f)),
             (sr_color.b < 0.5f) ? (1.0f - (((1.0f - sr_color.b) * 0.5f) / _119))
                                 : (sr_color.b / mad(0.5f - _119, 2.0f, 1.0f)));
      }
   }
   else
   {
      float4 _140 =
          g_tPreviousColor[0].Sample(g_sLinearClamp, float2(mad(gl_FragCoord.x, _124, g_vSSAAJitterOffset[1].x),
                                                            mad(gl_FragCoord.y, _125, g_vSSAAJitterOffset[1].y)));
      float4 _153 =
          g_tPreviousColor[1].Sample(g_sLinearClamp, float2(mad(gl_FragCoord.x, _124, g_vSSAAJitterOffset[2].x),
                                                            mad(gl_FragCoord.y, _125, g_vSSAAJitterOffset[2].y)));
      float4 _169 =
          g_tPreviousColor[2].Sample(g_sLinearClamp, float2(mad(gl_FragCoord.x, _124, g_vSSAAJitterOffset[3].x),
                                                            mad(gl_FragCoord.y, _125, g_vSSAAJitterOffset[3].y)));
      float _180 = mad(gl_FragCoord.x, _124, g_vSSAAJitterOffset[0].x);
      float _181 = mad(gl_FragCoord.y, _125, g_vSSAAJitterOffset[0].y);
      float2 _183 = float2(_180, _181);
      float4 _185 = g_tColor.Sample(g_sLinearClamp, _183);
      float4 _191 = g_tClipDepth.Sample(g_sLinearClamp, _183);
      float _192 = _191.x;
      gl_FragDepth = _192;
      float _193 = ((_140.x + _153.x) + _169.x) + _185.x;
      float _194 = _185.y + (_169.y + (_140.y + _153.y));
      float _195 = _185.z + (_169.z + (_140.z + _153.z));
      SV_Target.x = (_193 < 2.0f) ? (1.0f - ((mad(_193, -0.25f, 1.0f) * 0.5f) / _117))
                                  : ((_193 * 0.25f) / mad(0.5f - _117, 2.0f, 1.0f));
      SV_Target.y = (_194 < 2.0f) ? (1.0f - ((mad(_194, -0.25f, 1.0f) * 0.5f) / _118))
                                  : ((_194 * 0.25f) / mad(0.5f - _118, 2.0f, 1.0f));
      SV_Target.z = (_195 < 2.0f) ? (1.0f - ((mad(_195, -0.25f, 1.0f) * 0.5f) / _119))
                                  : ((_195 * 0.25f) / mad(0.5f - _119, 2.0f, 1.0f));
   }

   SV_Target.rgb = ApplyDisplayMapAndScale(SV_Target.rgb, scaled_uv, _104.z);
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
   gl_FragCoord = stage_input.gl_FragCoord.xy;
   frag_main();
   SPIRV_Cross_Output stage_output;
   stage_output.gl_FragDepth = gl_FragDepth;
   stage_output.SV_Target = SV_Target;
   return stage_output;
}
